#!/usr/bin/perl
use strict;
use warnings;

my $server = "http://checkip.dyndns.org";

my $ipGet = `wget -q -O - $server`;
if($ipGet =~ /\d+\.\d+\.\d+\.\d+/){
  print "$&\n";
}else{
  die "Couldn't get IP from $server\n";
}
