#!/usr/bin/perl
# twips: TWitter IP Server (this file is part of Twip)
# Copyright 2010,2012 Elliot Wolk
# License: GNU GPL version 3 or any later version
use strict;
use warnings;

my $LOG_FILE = '~/.twiplog';
my $TIMEOUT = 30;

my $start;

sub twiplog($){
  my $msg = shift;
  my $time = localtime time;
  system "echo '$time: $msg' >> ~/.twiplog";
}
sub fail($){
  my $err = shift;
  twiplog $err;
  die $err;
}

my $ip = '';
$start = time;
while($ip !~ /^([0-9]+\.)*[0-9]+$/){
  if(time - $start >= $TIMEOUT){
    fail 'Failure: could not obtain IP';
  }
  print "Trying to fetch IP...\n";
  $ip = `extip`;
  $ip =~ s/[ \t\n]//g;
  print "  response: $ip\n";
  sleep 2;
}

print "Fetched IP: $ip\n";

my $newIP = '';
$start = time;
while($newIP ne $ip){
  if(time - $start >= $TIMEOUT){
    fail "Failure: could not tweet IP {$ip}";
  }
  print "Trying to tweet IP...\n";
  system "twip -p --ip $ip";
  print "Trying to verify tweeted IP...\n";
  $newIP = `twip -g`;
  $newIP =~ s/[ \t\n]//g;
  print "Got from twitter: $newIP\n";
  if($newIP ne $ip){
    print "retrying after 5s...";
    sleep 5;
  }
}

twiplog "Success: $newIP";
print "Verified tweeted IP (yay!): $newIP\n";

